
server:
  port: 9091
---
spring:
  profiles: 
    active:
    - dev
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/toures_domain_usuario
    username: root
    password: root
  application:
    name: toures-balon-usuario
eureka:
  client:
  #  service-url: {"http://toures-balon-discovery:8761/eureka"}
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    prefer-ip-address: true
userNotFoundMessage: "Usuario no Encontrado"